from unittest.mock import MagicMock, patch

import httpx

from app.core.config import settings
from app.services.ai.llm_provider import (
    MockLlmProvider,
    OllamaLlmProvider,
    get_llm_provider,
)


def test_mock_llm_provider_summary():
    provider = MockLlmProvider()
    response = provider.generate_text("Summarize Atomic Habits")
    assert "elevator pitch" in response.lower()
    assert "key lessons" in response.lower()

def test_mock_llm_provider_compare():
    provider = MockLlmProvider()
    response = provider.generate_text("Compare book 1 vs book 2")
    assert "comparison summary" in response.lower()
    assert "|" in response  # Contains Markdown table

def test_mock_llm_provider_recommend():
    provider = MockLlmProvider()
    response = provider.generate_text("I want a recommendation")
    assert "recommend" in response.lower()

def test_mock_llm_provider_default():
    provider = MockLlmProvider()
    response = provider.generate_text("Who wrote Sapiens?")
    assert "provided book context" in response.lower()

def test_ollama_provider_success():
    provider = OllamaLlmProvider()

    # Mock httpx.Client context manager and its post method
    with patch("httpx.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "message": {
                "content": "This is a response generated by Ollama."
            }
        }
        mock_client.post.return_value = mock_response
        mock_client_class.return_value.__enter__.return_value = mock_client

        response = provider.generate_text("Hello Ollama")
        assert response == "This is a response generated by Ollama."

def test_ollama_provider_offline_fallback():
    provider = OllamaLlmProvider()

    # Mock connection failure inside Client session
    with patch("httpx.Client") as mock_client_class:
        mock_client = MagicMock()
        mock_client.post.side_effect = httpx.ConnectError("Connection timed out")
        mock_client_class.return_value.__enter__.return_value = mock_client

        # Should fallback to MockLlmProvider instead of raising an error
        response = provider.generate_text("Summarize Atomic Habits")
        assert "elevator pitch" in response.lower()

def test_get_llm_provider_factory(monkeypatch):
    # Test getting mock provider by default
    monkeypatch.setattr(settings, "LLM_PROVIDER", "mock")
    provider = get_llm_provider()
    assert isinstance(provider, MockLlmProvider)

    # Test getting ollama provider
    monkeypatch.setattr(settings, "LLM_PROVIDER", "ollama")
    provider = get_llm_provider()
    assert isinstance(provider, OllamaLlmProvider)
